---
output: 
    html_document:
        theme: readable
---

### Quantitative Economics (Spring 2016)

Instructor: [Jing Fang](http://bayeswhu.github.io)

Office: 419, School of Economics

Email: [jing_fang@hust.edu.cn](jing_fang@hust.edu.cn)

-----

### Course Materials

#### Slides

- [Lec 0](qe/Lec0.html)

- Part 1 Programming in Python
    + [Lec 1 About Python](qe/Lec1.html)
    + [Lec 2 Setting up Your Python Environment](qe/Lec2.html)
    + [Lec 3 An Introductory Example](qe/Lec3.html)
    + [Lec 4 Python Essentials](qe/Lec4.html)
    + [Lec 5 Object Oriented Programming](qe/Lec5.html)
    + [Lec 6 NumPy](qe/Lec6.html)
    + [Lec 7 SciPy](qe/Lec7.html)
    + [Lec 8 Matplotlib](qe/Lec8.html)
    + [Lec 9 Pandas](qe/Lec9.html)
    + [Lec 10 IPython Shell and Notebook](qe/Lec10.html)
    + [Lec 11 The Need for Speed](qe/Lec11.html)

  
- part 2 Introductory Applications
    + [Lec 12 Linear Algebra](qe/Lec12.html)
    + [Lec 13 Finite Markov Chains](qe/Lec13.html)
    + [Lec 14 Shortest Paths](qe/Lec14.html)
    + [Lec 15 Schelling's Segregation Model](qe/Lec15.html)
    + [Lec 16 LLN and CLT](qe/Lec16.html)
    + [Lec 17 Linear State Space Models](qe/Lec17.html)<!-- -->

#### Exercise Keys

- Part 1
    + [Key 3](qe/Lec3_Key.ipynb)
    + [Key 4](qe/Lec4_Key.ipynb)
    + [Key 5](qe/Lec5_Key.ipynb)
    + [Key 6](qe/Lec6_Key.ipynb)
    + [Key 7](qe/Lec7_Key.ipynb)
    + [Key 9](qe/Lec9_Key.ipynb)
    + [Key 11](qe/Lec11_Key.ipynb)

- Part 2
    + [Key 13](qe/Lec13_Key.ipynb)

#### Quiz

- [Quiz_2016_04_14](qe/Quiz.html)