---
output: 
    html_document:
        theme: readable
---

### International Trade (Fall 2016)

Instructor: [Jing Fang](http://bayeswhu.github.io)

Office: 419, School of Economics

Email: [jing_fang@hust.edu.cn](jing_fang@hust.edu.cn)

-----

### Course Materials

#### Slides

- [Introduction](trade/Introduction.ppt)

- [Lec 1](trade/Ch01.ppt)

- [Lec 2](trade/Ch02.ppt)

- [Lec 3](trade/Ch03.ppt)

- [Lec 4](trade/Ch04.ppt)

- [Lec 5](trade/Ch05.ppt)

- [Lec 6](trade/Ch06.ppt)

- [Lec 7](trade/Ch07.ppt)

- [Lec 8](trade/Ch08.ppt)

- [Lec 9](trade/Ch09.ppt)

- [Lec 10](trade/Ch10.ppt)

- [Lec 11](trade/Ch11.ppt)

- [Lec 12](trade/Ch12.ppt) 

<!-- -->
#### Homeworks

- [Homework 1](trade/Homework1.doc)

- [Homework 2](trade/Homework2.doc) <!-- -->

#### Keys

- [Key 1](trade/Hw1_key.doc)

- [Key 2](trade/Hw2_key.doc) <!-- -->

#### Quiz

- [Quiz 1](trade/Quiz1.ppt)

<!-- - [Quiz 2](trade/Quiz2.ppt)

- [Quiz 3](trade/Quiz3.ppt) -->

#### Project

- [Project List](trade/Project.ppt)  <!-- -->

#### Presentation

- [Lec 3](trade/cs03.docx)

- [Lec 4](trade/cs04.docx)

- [Lec 5](trade/cs05.docx)

- [Lec 6](trade/cs06.docx)

- [Lec 7](trade/cs07.docx)

- [Lec 8](trade/cs08.docx)

- [Lec 9](trade/cs09.docx)

- [Lec 10](trade/cs10.docx)

- [Lec 11](trade/cs11.docx)

- [Lec 12](trade/cs12.docx)