---
output: 
    html_document:
        css: my_markdown.css
        mathjax: null
---

### Topic 1: Dynamic Oligopoly, Entry 

#### Theory

- Doraszelski, Ulrich and Ariel Pakes, "A Framework for Applied Dynamic Analysis in IO", Mark Armstrong and Robert Porter (eds.), Handbook of Industrial Organization, Volume 3, Chapter 30, Pages 1887-1966 (2007).

- Maskin, Eric and Jean Tirole (1988), "A Theory of Dynamic Oligopoly I: Overview and Quantity Competition" and "A Theory of Dynamic Oligopoly II: Price Competition, Kinked Demand Curves, and Edgeworth Cycles" Econometrica 56, 549-599.

- Gowrisankaran G. and T. Holmes, "Mergers and the Evolution of Industry Concentration: Results from the Dominant Firm Model," Rand, Autumn, 2004.

- Pakes, A., Ostrovsky, M., Berry, S. (2007). "Simple estimators for the parameters of discrete dynamic games (with entry/exit examples)". RAND Journal of Economics Vol. 38, No. 2, Summer 200. 

- Patrick Bajari, C. Lanier Benkard and Jonathan Levin, "Estimating Dynamic Models of Imperfect Competition," Econometrica Vol. 75, No. 5 (Sep., 2007) (pp. 1331-1370)

#### Applications

- Ryan, S. P. (2012), The Costs of Environmental Regulation in a Concentrated Industry. Econometrica, 80: 1019–1061.

- Miller, Nathan and Matthew Osbourne, "Competition Among Spatially Differentiated Firms: An Estimator with an Application to Cement," Nov 2012 working paper, forthcoming Rand

- Dunne, Timothy, Shawn Klimek, and James A. Schmitz, Jr., "Does Competition Spur Productivity? Evidence From Post WWII U.S. Cement Manufacturing,"  Federal Reserve Bank Working Paper, 2011 working paper
 
- Victor Aguirregabiria and Chun-Yu Ho, "A dynamic oligopoly game of the US airline industry: Estimation and policy experiments, Journal of Econometrics, Volume 168, Issue 1, May 2012, Pages 156-173, 

- Seim, K. (2006): "An Empirical Model of  Firm Entry with Endogenous Product-Type Choices," RAND Journal of Economics, ol. 37, No. 3 (Autumn, 2006) (pp. 619-640)

- Barwick, Panle Jia, and Parag Pathak, "The Costs of Free Entry: An Empirical Study of Real Estate Agents in Greater Boston," forthcoming Rand

- Kalouptsidi, Myrto. 2014. "Time to Build and Fluctuations in Bulk Shipping." American Economic Review, 104(2): 564-608.

- Sutton, John, "Market Structure: Theory and Evidence,"  Handbook of Industrial Organization Volume 3, 2007, Pages 2301–2368
 
### Topic 2 Pricing and Auctions
 
- Ken Hendricks, Robert H. Porter," An Empirical Perspective on Auctions, " Handbook of Industrial Organization, Volume 3, Chapter 32, Pages 2073-2143

- Aradillas-López, A., Gandhi, A. and Quint, D. (2013), Identification and Inference in Ascending Auctions With Correlated Private Values. Econometrica, 81: 489–534.

- Hortaçsu, A. and Kastl, J. (2012), Valuing Dealers' Informational Advantage: A Study of Canadian Treasury Auctions. Econometrica, 80: 2511–2542.

- Nevo, Aviv and Turner, John L. and Williams, Jonathan W., Usage-Based Pricing and Demand for Residential Broadband (September 24, 2013).

- Maskin, Eric and John Riley, "Monopoly with Incomplete Information, "The RAND Journal of Economics, Vol. 15, No. 2 (Summer, 1984), pp. 171-196
 
### Topic 3: Productivity, Firm Growth, and the Size Distribution of Firms
 
- Lucas, Robert "On the Size Distribution of Business Firms," Bell Journal, 1978, 508-523

- Hopenhayn, Hugo, "Entry, Exit, and firm Dynamics in Long Run Equilibrium," Econometrica  Vol. 60, No. 5 (Sep., 1992), pp. 1127-1150

- Eaton and Kortum, "Technology, Geography, and Trade, Econometrica, 70(5), 2002, 1741-1779.

- Andrew B. Bernard; Jonathan Eaton; J. Bradford Jensen; Samuel Kortum, "Plants and Productivity in International Trade The American Economic Review, Vol. 93, No. 4. (Nov., 2003), pp. 1268-1290.

- Holmes and Stevens, "An Alternative Theory of the Plant Size Distribution,with Geography and Intra- and International Trade," September 2013

- Luttmer, Erzo "On the Mechanics of Firm Growth," The Review of Economic Studies, Review of Economic Studies (2011) 78 (3): 1042-1068.

### Topic 4: Knowledge Spillovers
  
- Ahlfedlt, Gabriel, Steven Redding, Daniel Sturm and Nikolaus Wolf," The  Economics of Density: Evidence from the Berlin Wall ," NBER Working Paper, 20354, July 2014 
 
- Covert, Thomas, "Experiential and social learning in firms: the case of hydraulic fracturing in the Bakken Shale." manuscript, May 2014.
 
- Philippe  Aghion,  Antoine  Dechezleprêtre,  David  Hemous,  Ralf  Martin,  John  Van Reenen, "Carbon Taxes, Path Dependency and Directed Technical Change: Evidence from the Auto Industry," November 2012
 
- Zvi Griliches, "Hybrid Corn and the Economics of Innovation," Science, New Series, Vol. 132, No. 3422. (Jul. 29, 1960), pp. 275-280.
  
- Felix Tintelnot, "Global Production with Export Platforms, April 2014

- Holmes,  The Diffusion of Wal-Mart and Economies of Density," Econometrica, Vol. 79, No. 1 (January, 2011), 253-302

- Helpman, Melitz, Yeaple, "Export versus FDI with Heterogeneous Firms," American Economic Review 2004

- Holmes, Thomas," "The Location of Sales Offices and the Attraction of Cities," Journal of Political Economy, Vol. 113, No. 3, June 2005, 551-581.